### ISSUE TITLE
Cannot run the tool to assess software quality with code climate model

### ISSUE THREAD

**Issue by HelgeCPH** [parameterIT/tool#85]
After cloning the repository and after cloning and building the tree-sitter sources, I get the following error when I try to assess software quality with code climate model:

```bash
$ poetry run main . code_climate python
Traceback (most recent call last):
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1720, in close
    self.parser.Parse(b"", True) # end of data
xml.parsers.expat.ExpatError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "$HOME/.cache/pypoetry/virtualenvs/byoqm-9fkXLX7W-py3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "$HOME/.cache/pypoetry/virtualenvs/byoqm-9fkXLX7W-py3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "$HOME/.cache/pypoetry/virtualenvs/byoqm-9fkXLX7W-py3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "$HOME/.cache/pypoetry/virtualenvs/byoqm-9fkXLX7W-py3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File /.../ByoQM-tool/byoqm/main.py", line 88, in load
    runner.run()
  File /.../ByoQM-tool/byoqm/runner/runner.py", line 68, in run
    results = self._run_aggregations()
  File /.../ByoQM-tool/byoqm/runner/runner.py", line 82, in _run_aggregations
    results = self._run_metrics()
  File /.../ByoQM-tool/byoqm/runner/runner.py", line 105, in _run_metrics
    results[metric] = module.metric.run()
  File /.../ByoQM-tool/./metrics/identical_codeblocks.py", line 17, in run
    return self._identical_blocks_of_code()
  File /.../ByoQM-tool/./metrics/identical_codeblocks.py", line 40, in _identical_blocks_of_code
    element_tree = parse(StringIO(res.stdout))
  File "$HOME/.cache/pypoetry/virtualenvs/byoqm-9fkXLX7W-py3.10/lib/python3.10/site-packages/defusedxml/common.py", line 100, in parse
    return _parse(source, parser)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 587, in parse
    self._root = parser.close()
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1722, in close
    self._raiseerror(v)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1622, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

**Comment by SadCheeto** [comment]
This is a problem we are currently working on solving. We have issues running Copy Paste Detector (CPD) on the M1/M2 mac chips. I am assuming you own a new(ish) Mac with this chip?

**Comment by HelgeCPH** [comment]
Cool. No I am running this on an AMD Ryzen PRO5 on:

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy
```
