### ISSUE TITLE
Cannot run the tool to assess software quality with `tester_model` model

### ISSUE THREAD

**Issue by HelgeCPH** [parameterIT/tool#86]
After cloning the repository and after cloning and building the tree-sitter sources, I get the following error when I try to assess software quality with code `tester_model`:

```bash
$ poetry run main . tester_model python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "$HOME/.cache/pypoetry/virtualenvs/byoqm-9fkXLX7W-py3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "$HOME/.cache/pypoetry/virtualenvs/byoqm-9fkXLX7W-py3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "$HOME/.cache/pypoetry/virtualenvs/byoqm-9fkXLX7W-py3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "$HOME/.cache/pypoetry/virtualenvs/byoqm-9fkXLX7W-py3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/.../byoqm/main.py", line 88, in load
    runner.run()
  File "/.../byoqm/runner/runner.py", line 70, in run
    self._gen_output_paths_if_not_exists()
  File "/.../byoqm/runner/runner.py", line 173, in _gen_output_paths_if_not_exists
    Path(self._output_dir / Path("violations")).resolve().mkdir(exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/.../output/violations'
```

**Comment by HelgeCPH** [comment]
I would suggest that you create directories with a `.gitkeep` file that you expect to be there at runtime

**Comment by SadCheeto** [comment]
fixed in https://github.com/parameterIT/tool/pull/88
